color_scheme: dark
title: My Blog
email: mariodmpereira@gmail.com
description: >-
  This is my personal Developer Handbook to keep track of my learnings.
# baseurl: ""
url: "https://www.mariodmpereira.com"
github_username:  mariodmpereira
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

aux_links:
  "GitHub":
    - "//github.com/mariodmpereira/"
  "Linkedin":
    - "//linkedin.com/in/mariodmpereira/"